/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://7h4in7wmijc4vj2adfu454s74u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3oqw3w4dcnd6lazsroobuuj5hu",
    "aws_cognito_identity_pool_id": "us-east-1:8e297d8c-1688-44ca-b5e0-c635c8143807",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0k0N1jz66",
    "aws_user_pools_web_client_id": "74lirpovj03ha3qsnav843fefe",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "rndemo-storage-351ba985a3a0f-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
